turt1eRun/turtle-run

- src/main/java/trend_setter/turtlerun/inquiry/entity/Inquiry.java
- src/main/java/trend_setter/turtlerun/inquiry/entity/InquiryStatus.java
- src/main/java/trend_setter/turtlerun/inquiry/entity/InquriyResponse.java
resolve #3 
문의 관련 엔티티 추가
Inquiry, InquiryResponse 엔티티 생성
> [Feat] Inquiry 엔티티 추가

- src/main/java/trend_setter/turtlerun/user/Role.java
- src/main/java/trend_setter/turtlerun/user/User.java
resolve #1 
PR의 개요를 적어주세요.
User 엔티티 추가
> [Feat] User 엔티티 추가

- src/main/java/trend_setter/turtlerun/inquiry/entity/Faq.java
resolve #6 
자주하는 문의 엔티티 추가
Faq 엔티티 추가
> [Feat] FAQ 엔티티 추가

- src/main/java/trend_setter/turtlerun/wallet/entity/Charge.java
- src/main/java/trend_setter/turtlerun/wallet/entity/Donation.java
- src/main/java/trend_setter/turtlerun/wallet/entity/Refund.java
- src/main/java/trend_setter/turtlerun/wallet/entity/TransactionStatus.java
- src/main/java/trend_setter/turtlerun/wallet/entity/TransactionType.java
- src/main/java/trend_setter/turtlerun/wallet/entity/Wallet.java
- src/main/java/trend_setter/turtlerun/wallet/entity/WalletHistory.java
- resolve #4
Wallet 엔티티 추가
Wallet 및 연관 엔티티 추가
> [Feat] Wallet 엔티티 추가

- src/main/java/trend_setter/turtlerun/global/content/entity/BlockType.java
- src/main/java/trend_setter/turtlerun/global/content/entity/Content.java
- src/main/java/trend_setter/turtlerun/global/content/entity/DescriptionBlock.java
- src/main/java/trend_setter/turtlerun/global/content/entity/DescriptionFile.java
- src/main/java/trend_setter/turtlerun/global/content/entity/ThumbnailFile.java
- src/main/java/trend_setter/turtlerun/global/content/entity/Video.java
- src/main/java/trend_setter/turtlerun/global/content/entity/VideoFile.java
- src/main/java/trend_setter/turtlerun/global/content/entity/VideoHistory.java
- src/main/java/trend_setter/turtlerun/global/content/entity/VideoResolution.java
- src/main/java/trend_setter/turtlerun/global/content/entity/VideoStatus.java
> [FEAT] Content 관련 엔티티 추가

- src/main/java/trend_setter/turtlerun/wallet/entity/Refund.java
- src/main/java/trend_setter/turtlerun/wallet/entity/RefundType.java
- resolve #16
환급 타입 추가
RefundType 추가
> [Feat] 환급 타입 추가

- src/main/java/trend_setter/turtlerun/wallet/entity/Charge.java
- src/main/java/trend_setter/turtlerun/wallet/entity/Donation.java
- src/main/java/trend_setter/turtlerun/wallet/entity/Refund.java
- resolve #20
Charge, Donation, Refund 생성 메서드 status 수정
각 생성 메서드 status 수정
> [Bug] Charge, Donation, Refund 초기 Status 값 수정

- src/main/java/trend_setter/turtlerun/content/entity/BlockType.java
- src/main/java/trend_setter/turtlerun/content/entity/Content.java
- src/main/java/trend_setter/turtlerun/content/entity/DescriptionBlock.java
- src/main/java/trend_setter/turtlerun/content/entity/DescriptionFile.java
- src/main/java/trend_setter/turtlerun/content/entity/ThumbnailFile.java
- src/main/java/trend_setter/turtlerun/content/entity/Video.java
- src/main/java/trend_setter/turtlerun/content/entity/VideoFile.java
- src/main/java/trend_setter/turtlerun/content/entity/VideoHistory.java
- src/main/java/trend_setter/turtlerun/content/entity/VideoResolution.java
- src/main/java/trend_setter/turtlerun/content/entity/VideoStatus.java
- resolve #22 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
> [FIX] content 패키지 경로 수정

- src/main/java/trend_setter/turtlerun/subscription/entity/Subscription.java
- resolve #25 
구독 관련 엔티티 추가
Subscription 엔티티 생성
> [Feat] Subscription 엔티티 추가

- src/main/java/trend_setter/turtlerun/like/entity/Like.java
- resolve #27 
좋아요 엔티티 추가
Like 엔티티 생성
> [Feat] Like 엔티티 추가

- src/main/java/trend_setter/turtlerun/notification/entity/Notification.java
- src/main/java/trend_setter/turtlerun/notification/entity/NotificationReceipt.java
- src/main/java/trend_setter/turtlerun/notification/entity/NotificationSetting.java
- src/main/java/trend_setter/turtlerun/notification/entity/NotificationType.java
- resolve #29 
알림 관련 엔티티 추가
Notification, NotificationSetting, NotificationReceipt 엔티티 생성
> [Feat] Notification 관련 엔티티 추가

- src/main/java/trend_setter/turtlerun/content/entity/Content.java
- src/main/java/trend_setter/turtlerun/content/entity/VideoHistory.java
- resolve #32 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
> [FIX] user 엔티티 경로 추가

- src/main/java/trend_setter/turtlerun/connection/entity/Connection.java
- src/main/java/trend_setter/turtlerun/connection/entity/ConnectionType.java
- resolve #34 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
> [FEAT] Connection 관련 엔티티 추가

- src/main/java/trend_setter/turtlerun/inquiry/controller/InquiryController.java
- src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryDetailDto.java
- src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryListDto.java
- src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryWriteDto.java
- src/main/java/trend_setter/turtlerun/inquiry/repository/InquiryRepository.java
- src/main/java/trend_setter/turtlerun/inquiry/service/InquiryService.java
- src/main/java/trend_setter/turtlerun/inquiry/utils/InquiryMapper.java
- resolve #35 
문의하기 기능을 구현합니다.
문의 목록 조회, 문의 상세 조회, 문의 작성 기능을 구현하였습니다.
우선 명세서에서 createInquiry, getInquiries, getInquiryDetails 에 해당하는 부분만 1차적으로 구현하였습니다.
> [Feat] 문의하기 기능 1차 구현

- src/main/java/trend_setter/turtlerun/report/constant/ReportStatus.java
- src/main/java/trend_setter/turtlerun/report/constant/ReportType.java
- src/main/java/trend_setter/turtlerun/report/entity/ConnectionReport.java
- src/main/java/trend_setter/turtlerun/report/entity/ContentReport.java
- src/main/java/trend_setter/turtlerun/report/entity/ReportHistory.java
- src/main/java/trend_setter/turtlerun/report/entity/ReportReason.java
- resolve #41 
신고 엔티티 추가
컨텐츠 신고 엔티티 추가
커넥션 신고 엔티티 추가
신고 사유 엔티티 추가
신고 처리 내역 엔티티 추가
> [Feat] 신고 엔티티 추가

- src/main/java/trend_setter/turtlerun/global/config/SecurityConfig.java
- src/main/java/trend_setter/turtlerun/user/constant/Role.java
- src/main/java/trend_setter/turtlerun/user/controller/UserController.java
- src/main/java/trend_setter/turtlerun/user/dto/LoginRequest.java
- src/main/java/trend_setter/turtlerun/user/dto/LoginResponse.java
- src/main/java/trend_setter/turtlerun/user/dto/RegisterUserRequest.java
- src/main/java/trend_setter/turtlerun/user/entity/User.java
- src/main/java/trend_setter/turtlerun/user/jwt/JwtTokenProvider.java
- src/main/java/trend_setter/turtlerun/user/jwt/JwtUtils.java
- src/main/java/trend_setter/turtlerun/user/repository/UserRepository.java
- src/main/java/trend_setter/turtlerun/user/service/UserService.java
- resolve #12
PR의 개요를 적어주세요.
- 회원가입 기능 구현
- 로그인 기능 구현
- Role 클래스 constant 패키지로 이동
- User 클래스 entity 패키지로 이동
JWT 인증 방식 적용 예정
> [Feat] 회원가입 기능, 로그인 기능 구현

- src/main/java/trend_setter/turtlerun/inquiry/controller/InquiryController.java
- src/main/java/trend_setter/turtlerun/inquiry/repository/InquiryRepository.java
- src/main/java/trend_setter/turtlerun/inquiry/service/InquiryService.java
- resolve #58 
문의 기능 리팩토링
문의 목록 조회 페이지네이션 처리 완료
> [Feat] Inquiry 기능 리팩토링

- frontend/.gitignore
- frontend/Dockerfile
- frontend/next.config.ts
- frontend/nginx/default.conf
- frontend/src/app/layout.tsx
- frontend/src/app/login/layout.tsx
- frontend/src/components/common/Header.tsx
- resolve #65 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
> [Feat] CI/CD 구현

- src/main/java/trend_setter/turtlerun/report/entity/ConnectionReport.java
- src/main/java/trend_setter/turtlerun/report/entity/ContentReport.java
- src/main/java/trend_setter/turtlerun/report/entity/ReportHistory.java
- resolve #66 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
> [Bug] User import 경로 수정

- .github/workflows/deploy.yml
- resolve #78 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
> [Bug] CI/CD 배포 코드 변경

- .github/workflows/deploy.yml
- resolve #81 
PR의 개요를 적어주세요.
작업한 내용을 적어주세요.
> [Bug] CI/CD 배포 paths 수정 
